### ISSUE TITLE
Library should be empty for >= 4.07?

### ISSUE THREAD

**Issue by nojb** [c-cube/seq#12]
Currently the `seq` library re-exports `Stdlib.Seq` for versions of OCaml >= 4.07. This causes problems when using `(implicit_transitive_deps false)` in Dune (see eg https://github.com/ocaml/merlin/issues/1500).

Wouldn't it be better to simply define an _empty_ library for 4.07 and later, so that clients of this library would directly depend on `Stdlib.Seq` which would avoid the above problem?

**Comment by c-cube** [comment]
0.3 is on opam and should include this fix.
