### ISSUE TITLE
Please update opam file to match license of code

### ISSUE THREAD

**Issue by edwintorok** [c-cube/seq#2]
The opam file says the license is GPL, the source code of seq.ml says it is LGPL2.1 with special exception (same as the compiler's).
Since this is a compatibility library for the compiler's standard library please update the license in opam, there are a lot of packages in opam that are MIT or LGPL and having a GPL compatibility library means they couldn't use it.

**Comment by olafhering** [comment]
The README was not updated to reflect the new license `LGPL-2.1-only WITH OCaml-LGPL-linking-exception`.
