### ISSUE TITLE
opam demands ocaml-version < "4.07.0"

### ISSUE THREAD

**Issue by lindig** [c-cube/seq#3]
The opam file here and the one in in the official opam repository differ. The official one constrains the OCaml version while the one here does not. Which one is correct?

**Comment by lindig** [comment]
```

**Comment by lindig** [comment]
```

opam-version: "1.2"
maintainer: "simon.cruanes.2007@m4x.org"
authors: "Simon Cruanes"
homepage: "https://github.com/c-cube/seq/"
bug-reports: "https://github.com/c-cube/seq/issues"
license: "GPL"
tags: ["iterator" "seq" "pure" "list" "compatibility" "cascade"]
dev-repo: "https://github.com/c-cube/seq.git"
build: [make "build"]
install: [make "install"]
remove: [ "ocamlfind" "remove" "seq" ]
depends: [
  "ocamlfind" {build}
  "ocamlbuild" {build}
]
available: [ocaml-version < "4.07.0"]
```

**Comment by c-cube** [comment]
This is a compatibility package, since the `Seq` module is included in OCaml starting from 4.07. There should be another package in opam-repo that does nothing for OCaml 4.07.

**Comment by lindig** [comment]
I came across this because `re.1.8.0` lists `seq` as a dependency. Would an OCaml 4.07 installation include a `seq.base` opam file such that this dependency is met?

**Comment by c-cube** [comment]
Well `opam info seq.base` indicates that it's `>= 4.07`, so it should
work (modulo bugs)! :)

**Comment by lindig** [comment]
Let's close this. But maybe some comment in the opam file in this repository would be helpful.
