### ISSUE TITLE
make a new release

### ISSUE THREAD

**Issue by c-cube** [c-cube/seq#6]

**Comment by aantron** [comment]
Could you include this branch, which ports seq to Dune? It should subsume the recent PR.

https://github.com/dune-universe/seq/tree/duniverse-0.1

**Comment by aantron** [comment]
It looks like the opam metadata needs fixing. I'll make a proper PR. EDIT: #7.

**Comment by c-cube** [comment]
started release: https://github.com/ocaml/opam-repository/pull/14998
